version: "3"

services:
  site:
    container_name: site
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    networks:
      main:
    volumes:
      - ./misc/:/bin/app/misc/:ro
      - ./pages/:/bin/app/pages/:ro
      - ./songs/:/bin/app/songs/:ro
      - ./static/:/bin/app/static/:ro
      - ./templates/:/bin/app/templates/:ro
      - ./Rocket.toml:/bin/app/Rocket.toml:ro
      - ./Cargo.toml:/bin/app/Cargo.toml:ro
      - ./Cargo.lock:/bin/app/Cargo.lock:ro

networks:
  main:
    external: true
