version: "3"

services:
  site:
    container_name: site
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    networks:
      main:
    volumes:
      - ./misc/:/usr/local/bin/misc/:ro
      - ./pages/:/usr/local/bin/pages/:ro
      - ./songs/:/usr/local/bin/songs/:ro
      - ./static/:/usr/local/bin/static/:ro
      - ./templates/:/usr/local/bin/templates/:ro
      - ./Rocket.toml:/usr/local/bin/Rocket.toml:ro



networks:
  main:
    external: true
